name: Java-Gradle CI

on:
  push:
    branches:
      - master
      - neoforge
      - 'mc/**'
  pull_request:
    branches:
      - master
      - neoforge
      - 'mc/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle
      run: ./gradlew build -Pmod_version=${{ github.run_id }}-artifact

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}
        path: build/libs/